name:                puzzle15
version:             0.1.0.0
github:              "alang76/puzzle15"
license:             BSD3
author:              "Arjen Langebaerd"
maintainer:          "arjen@langebaerd.net"
copyright:           "Copyright (c) 2019 Arjen Langebaerd"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            solver for advent of code puzzle
# category:            Code Competitions

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alang76/puzzle15#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 8.0.0
- array >= 0.5.3.0
- text >= 1.2.3.1
- mtl >= 2.2.2

executables:
  puzzle15-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  puzzle15-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - puzzle15

